@if($field instanceof \Smoothy\Api\Custom\Models\Field\PercentageField)
    @include('smoothy::form.custom.fields.percentageField')
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\PriceField)
    @include('smoothy::form.custom.fields.priceField')
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\DecimalField)
    @include('smoothy::form.custom.fields.decimalField')
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\ColorField)
    @include('smoothy::form.custom.fields.colorField')
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\DateField)
    @include('smoothy::form.custom.fields.dateField')
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\DateTimeField)
    @include('smoothy::form.custom.fields.dateTimeField')
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\EmailField)
    @include('smoothy::form.custom.fields.emailField')
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\IntegerField)
    @include('smoothy::form.custom.fields.integerField')
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\IpAddressField)
    @include('smoothy::form.custom.fields.ipAddressField')
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\PasswordField)
    @include('smoothy::form.custom.fields.passwordField')
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\SelectField)
    @include('smoothy::form.custom.fields.selectField')
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\TagsField)
    @include('smoothy::form.custom.fields.tagsField')
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\TimeField)
    @include('smoothy::form.custom.fields.timeField')
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\UrlField)
    @include('smoothy::form.custom.fields.urlField')
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\TextAreaField)
    @include('smoothy::form.custom.fields.textAreaField')
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\TranslationField)
    @include('smoothy::form.custom.fields.translationField')
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\WysiwygField)
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\TextField)
    @include('smoothy::form.custom.fields.textField')
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\BooleanField)
    @include('smoothy::form.custom.fields.booleanField')
@elseif($field instanceof \Smoothy\Api\Custom\Models\Field\FilesField)
    @include('smoothy::form.custom.fields.filesField')
@endif